%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Diego\Documents\Matlab works\ProgettoElettrotecnica-main\Scheda.xlsx
%    Worksheet: Inserimento dati
%
% Auto-generated by MATLAB on 05-Feb-2021 10:27:56

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Inserimento dati";
opts.DataRange = "A9:F18";

% Specify column names and types
opts.VariableNames = ["CodiceISSN", "CodiceIRIS", "Tipologia", "Punteggio", "Premiato", "DettagliDelRanking"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["CodiceISSN", "CodiceIRIS", "Tipologia", "Punteggio", "Premiato", "DettagliDelRanking"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CodiceISSN", "CodiceIRIS", "Tipologia", "Punteggio", "Premiato", "DettagliDelRanking"], "EmptyFieldRule", "auto");

% Import the data
Scheda = readmatrix("C:\Users\Diego\Documents\Matlab works\ProgettoElettrotecnica-main\Scheda.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts